### ISSUE TITLE
Missing installation instructions

### ISSUE THREAD

**Issue by tscheypidi** [JGCRI/hectorui#19]
Hi @evanoffPNNL,

I am currently looking for installation instructions how to install and run hectorui on my local system. Could you please add some instructions either to the README.md or tutorial file (how to install it & how to run the shiny app locally)?

This is related to https://github.com/openjournals/joss-reviews/issues/2782.

Thanks, Jan

**Comment by evanoffPNNL** [comment]
Included basic installation instructions in 1.1.4

**Comment by tscheypidi** [comment]
@evanoffPNNL Hi Jason, thanks for your update. What I am still missing in the README is an short explanation how to run the app locally. I could start it using `shiny::runApp(system.file("shinyApp",package = "hectorui"))`, but I am not sure whether this is the envisaged method.
