### ISSUE TITLE
Missing unit information

### ISSUE THREAD

**Issue by tscheypidi** [JGCRI/hectorui#20]
The custom emissions section does not seem to tell in which unit the custom emissions value is expected (Tg?). Please add this information.

(related to https://github.com/openjournals/joss-reviews/issues/2782)

**Comment by evanoffPNNL** [comment]
Tg is correct, I will add it to the application in that section so its more clear.

**Comment by evanoffPNNL** [comment]
Added (Tg) to page for clarification
