### ISSUE TITLE
Cite software used in hectorui

### ISSUE THREAD

**Issue by tscheypidi** [JGCRI/hectorui#22]
Please cite the shiny package in your paper (`citation("shiny")` can be used in R to retrieve the citation). If there are further software or software packages hectorui heavily relies on, but which is not mentioned/cited at the moment, please cite it as well.

Linked to: https://github.com/openjournals/joss-reviews/issues/2782

**Comment by evanoffPNNL** [comment]
Added citation in 1.1.4

**Comment by tscheypidi** [comment]
@evanoffPNNL Please also add the citation to the paper. Currently, the citation just seems to be added to the .bib file, but not referred to in the paper itself.
