### ISSUE TITLE
 Download spatial information in raster format

### ISSUE THREAD

**Issue by marvinjonathcn** [JGCRI/hectorui#28]
Hi @evanoffPNNL.

Is it possible to download the information generated in the global maps in raster format? . Currently the download only allows to obtain this information in .png format

Related to : [openjournals/joss-reviews#2782](https://github.com/openjournals/joss-reviews/issues/2782).

**Comment by evanoffPNNL** [comment]
At this time we are only supporting png, but your suggestion makes a lot of sense and we will add it to the list of suggested upgrades if that is sufficient?
