### ISSUE TITLE
Remove preindustrial CO2 parameter

### ISSUE THREAD

**Issue by stephpenn1** [JGCRI/hectorui#48]
From @bpbond: "I'm not sure it makes sense to let users adjust this...? It's a very precisely known historical quantity."

Variable in Hector: `pco2`

**Comment by stephpenn1** [comment]
@ssmithClimate what are your thoughts on having this removed in the tunable HectorUI parameters?

**Comment by bpbond** [comment]
The other thing is, _this doesn't matter_ (at least, not very much). Hector's carbon dynamics are ultimately determined by the total amount of C in the earth system and the first-order relationships between them, e.g. how much the land responds to  CO2 enrichment. If you change the preindustrial CO2 value the model is going to re-equilibrate during the historical transient period anyway.

**Comment by bpbond** [comment]
...I just mean, it can be in hectorui of course, but I think it'll have a _very_ small effect on model runs.

**Comment by ssmithClimate** [comment]
Agree that that's not a critical parameter for hectorUI. (Sorry I didn't see the context...)
