### ISSUE TITLE
Additional RCPs don't load correctly when parameters are changed

### ISSUE THREAD

**Issue by ciara-donegan** [JGCRI/hectorui#54]
When a parameter is changed, the plot is reloaded, and then additional RCPs are selected, the additional RCPs load as if the parameter has not been changed. Clicking "Load Graphs" again makes it appear as intended.

Example: CO2 fertilization factor was increased, the plot was reloaded, then additional RCPs were selected:
![pre reload](https://user-images.githubusercontent.com/82416895/192587664-bb3f0775-f535-4838-b64f-35818f1ea55e.png)

Then "Load Graphs" is clicked and the plot looks how it's supposed to:
![post reload](https://user-images.githubusercontent.com/82416895/192587451-a20303f5-9439-4871-9d06-8db046a9000a.png)

**Comment by stephpenn1** [comment]
Looks like when a new RCP is selected, it loads with the default parameters and not with what the user selected. Clicking "Load Graphs" reloads all RCPs
