### ISSUE TITLE
Permafrost toggle

### ISSUE THREAD

**Issue by ciara-donegan** [JGCRI/hectorui#65]
Add permafrost toggle in "Explore Hector" tab under SSP section.

Feature would allow users to include permafrost in their HectorUI runs.

**Comment by stephpenn1** [comment]
Talk to Kalyn and team about initial permafrost value, currently set to 865
> `setvar(core(), 0, PERMAFROST(), 865, "Gg C")`

**Comment by stephpenn1** [comment]
Kalyn said we're good to go! Will close this with a PR
