### ISSUE TITLE
Investigate error with custom emissions

### ISSUE THREAD

**Issue by stephpenn1** [JGCRI/hectorui#69]
- [x] Run the [current version](https://github.com/JGCRI/hectorui/tree/redesign/inst/shinyApp) in the `redesign` tab and reproduce the error 
- [x] Investigate where the error is coming from
- [x] If the error is easy to fix, fix in here and then copy over code into `h2`
- [x] If error is not easy to fix, can we pull the structure into `h2` and adapt it for the new files?
- [x] Update to new hector v3 emissions files for SSPs, located [here](https://github.com/JGCRI/hector/tree/main/inst/input/tables)

**Comment by ciara-donegan** [comment]
The issue in the current version is with the three HCFC variables (HCFC22, HCFC141b, and HCFC142b) being read in. Unsure yet exactly why they aren't working, but custom emissions can be run by just removing them from the emissions file. The attached RCP 4.5 template works in the current version of HectorUI.

[RCP45_custom_template_fixed.csv](https://github.com/JGCRI/hectorui/files/15250593/RCP45_custom_template_fixed.csv)

Setting custom emissions with Hector v3 actually has different issues -- the units in the emissions template files are incorrect, and three variables don't work properly: HFC245fa_constrain (the "fa" is missing in the header name in the template), HFC365_constrain, and HFC365_emissions (both exist in input tables but not as variables). The attached SSP 1-1.9 csv file works with Hector v3 (units and HFC245fa fixed, HFC365 vars removed).

[ssp119_emiss-constraints_rf_fixed.csv](https://github.com/JGCRI/hectorui/files/15250610/ssp119_emiss-constraints_rf_fixed.csv)

**Comment by stephpenn1** [comment]
Great, let's create patch templates for all RCPs

**Comment by stephpenn1** [comment]
For new version of HectorUI, use r6 class for running custom emissions

**Comment by ciara-donegan** [comment]
All RCP templates working with the current version of HectorUI (HCFC variables removed):
[RCP26_custom_template_fixed.csv](https://github.com/JGCRI/hectorui/files/15310582/RCP26_custom_template_fixed.csv)
[RCP45_custom_template_fixed.csv](https://github.com/JGCRI/hectorui/files/15310585/RCP45_custom_template_fixed.csv)
[RCP6_custom_template_fixed.csv](https://github.com/JGCRI/hectorui/files/15310587/RCP6_custom_template_fixed.csv)
[RCP85_custom_template_fixed.csv](https://github.com/JGCRI/hectorui/files/15310588/RCP85_custom_template_fixed.csv)
