### ISSUE TITLE
Forcing factors don't change future forcing, only historical

### ISSUE THREAD

**Issue by stephpenn1** [JGCRI/hectorui#78]
Submitter: @stephpenn1 on behalf HectorUI Tutorial feedback

**Describe the bug**
Aerosol forcing factor and volcanic forcing factor does not visually seem to affect future forcing

**To Reproduce**
1. Go to 'Explore Hector' tab
2. Change Volcanic forcing scaling factor

From user:
> does the aerosol scaling factor only apply to historical aerosol forcing? it does not seem to affect future forcing

>or maybe it does have an effect but it is very small, both historical and futureI see that the global temperature changes, but the radiative forcing does not. 

>So the scaling factor is having an effect on forcing, but it does not show up in the forcing plot. Maybe that's something that could be changed? Btw the same thing applies to the volcanic forcing scaling factor.

**Comment by bconeill88** [comment]
Just to clarify, I think the problem is actually that the aerosol and volcanic forcing scaling factors don't change forcing in the UI at all (neither historical nor future). They DO change temperature, so they are having an effect on the model, but just not showing up in the plots of forcing.

**Comment by stephpenn1** [comment]
Hi @bconeill88, an update on this - you're correct that changing the RFs do impact the model, but are not being updated in the individual forcing outputs. The hector dev team is aware of this bug (https://github.com/JGCRI/hector/issues/743 and https://github.com/JGCRI/hector/pull/745) and are working to fix it in their next release. 

For hectorUI, our temporary solution would be to remove the graphing capabilities for those RFs outputs (aerosols and volcanic forcing).

@kdorheim and I are curious your thoughts on the priority of fixing this? Since it would constitute a major version change to the model, the release may not happen until next year otherwise.

**Comment by bconeill88** [comment]
Hi Stephanie, thanks for the update, glad to hear you are working on this.
Since it is not a problem with how the model itself is working, I don't
think it is super high priority. The temporary fix and the plan to include
a permanent one in the next major release sounds reasonable to me.
